module.exports = [{
          date: 2,
          price: 100,
          originId: 'SOF',
          destinationId: 'YVR'
        }, {
          date: 4,
          price: 150,
          originId: 'SOF',
          destinationId: 'GVA'
        }, {
          date: 5,
          price: 150,
          originId: 'YVR',
          destinationId: 'GVA'
        }, {
          date: 6,
          price: 150,
          originId: 'SOF',
          destinationId: 'GVA'
        }, {
          date: 3,
          price: 150,
          originId: 'GVA',
          destinationId: 'YQB'
        }, {
          date: 4,
          price: 150,
          originId: 'GVA',
          destinationId: 'SOF'
        }]
